services:
  web:
    build: .
    command: >
      bash -c "python manage.py migrate &&
      daphne -b 0.0.0.0 -p 8000 JobJab.asgi:application"
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    env_file:
      - JobJab/.env
    environment:
      - DJANGO_SETTINGS_MODULE=JobJab.settings
    depends_on:
      - db
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - '5432:5432'

volumes:
  postgres_data: