# Generated by Django 5.2.1 on 2025-06-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscription_plan_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_plan_type',
            field=models.CharField(choices=[('Starter', 'Starter'), ('Growth', 'Growth'), ('Elite', 'Elite')], default='Starter'),
        ),
    ]
