# Generated by Django 5.2.1 on 2025-07-03 12:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_subscription_plan_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_plan_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_plan_type',
        ),
        migrations.AddField(
            model_name='subscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False, help_text='Whether the subscription is scheduled to cancel at period end'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('elite', 'Elite')], default='starter', help_text='The subscription plan type', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='current_period_end',
            field=models.DateTimeField(blank=True, help_text='End of the current billing period', null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='current_period_start',
            field=models.DateTimeField(blank=True, help_text='Start of the current billing period', null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('past_due', 'Past Due'), ('unpaid', 'Unpaid'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired'), ('trialing', 'Trialing')], help_text='The current status of the subscription', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='The Stripe subscription ID', max_length=255, null=True, unique=True),
        ),
    ]
