# Generated by Django 5.2.1 on 2025-07-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('Starter', 'Starter'), ('Growth', 'Growth'), ('Elite', 'Elite')], default='Starter', help_text='The subscription plan type', max_length=20),
        ),
    ]
