# Generated by Django 5.2.1 on 2025-07-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_subscriptionrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionrecord',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False, help_text='Whether the subscription is scheduled to cancel at period end'),
        ),
        migrations.AlterField(
            model_name='subscriptionrecord',
            name='current_period_end',
            field=models.DateTimeField(blank=True, help_text='End of the current billing period', null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionrecord',
            name='current_period_start',
            field=models.DateTimeField(blank=True, help_text='Start of the current billing period', null=True),
        ),
    ]
