# Generated by Django 5.2.1 on 2025-07-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_alter_subscriptionrecord_cancel_at_period_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripe_invoice_id',
            field=models.CharField(blank=True, help_text='The Stripe subscription ID', max_length=255, null=True, unique=True),
        ),
    ]
