# Generated by Django 5.2.1 on 2025-07-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_alter_subscription_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='stripe_invoice_id',
            field=models.CharField(blank=True, help_text='The Stripe subscription ID', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionrecord',
            name='stripe_invoice_id',
            field=models.CharField(blank=True, help_text='The Stripe subscription ID', null=True, unique=True),
        ),
    ]
