# Generated by Django 5.2.1 on 2025-06-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
