# Generated by Django 5.2.1 on 2025-06-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_organization_logo_alter_organization_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='personal_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
