# Generated by Django 5.2.1 on 2025-06-26 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_customuser_latitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Certificate', 'verbose_name_plural': 'Certificates'},
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='image',
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_file',
            field=models.FileField(blank=True, help_text='Upload PDF certificate file', null=True, upload_to='certificates/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Certificate file should be a PDF')]),
        ),
        migrations.AddField(
            model_name='certificate',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Mark if the certificate has been verified by admin'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='title',
            field=models.CharField(blank=True, help_text="Title of the certificate (e.g., 'Python Developer Certification')", max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(10, message='Certificate title is too short')]),
        ),
    ]
