# Generated by Django 5.2.1 on 2025-06-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_certificate_options_remove_certificate_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='certificate_previews/'),
        ),
    ]
