# Generated by Django 5.2.1 on 2025-07-05 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_certificate_preview_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
