# Generated by Django 5.2.1 on 2025-07-15 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_customuser_preferred_end_customuser_preferred_start'),
        ('subscriptions', '0005_subscription_price_subscription_stripe_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscription_membership',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscription'),
        ),
    ]
