# Generated by Django 5.2.1 on 2025-07-16 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_customuser_subscription_membership'),
        ('subscriptions', '0005_subscription_price_subscription_stripe_price_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscription_membership',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_subscription', to='subscriptions.subscription'),
        ),
    ]
