# Generated by Django 5.2.1 on 2025-07-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_customuser_subscription_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Seeker', 'Seeker'), ('Provider', 'Provider')]),
        ),
    ]
