# Generated by Django 5.2.1 on 2025-07-24 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='preferred_end',
            field=models.TimeField(blank=True, default=datetime.time(17, 0), null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='preferred_start',
            field=models.TimeField(blank=True, default=datetime.time(9, 0), null=True),
        ),
    ]
