# Generated by Django 5.2.1 on 2025-07-31 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_userblacklistprofile_blacklistitem_notification'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='core_notifi_related_8996fa_idx',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_content_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_object_id',
        ),
    ]
