# Generated by Django 5.2.1 on 2025-08-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_notification_core_notifi_related_8996fa_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('seeker', 'Seeker'), ('provider', 'Provider'), ('admin', 'Administrator')]),
        ),
    ]
