# Generated by Django 5.2.1 on 2025-08-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='chat_bubble_color',
            field=models.CharField(default='#32AE88', max_length=7),
        ),
        migrations.AddField(
            model_name='customuser',
            name='chat_bubble_shape',
            field=models.CharField(default='rounded', max_length=20),
        ),
    ]
