# Generated by Django 5.2.1 on 2025-08-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_customuser_chat_bubble_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('seeker', 'Seeker'), ('provider', 'Provider'), ('admin', 'Administrator')], default='seeker', max_length=20),
        ),
    ]
