# Generated by Django 5.2.1 on 2025-08-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('seeker', 'Seeker'), ('provider', 'Provider')], default='seeker', max_length=20),
        ),
    ]
