# Generated by Django 5.2.1 on 2025-07-03 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicelisting',
            name='location',
        ),
    ]
