# Generated by Django 5.2.1 on 2025-07-09 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_servicelisting_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicelisting',
            name='likes',
        ),
        migrations.AddField(
            model_name='servicelisting',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='services_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
