# Generated by Django 5.2.1 on 2025-07-10 19:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_servicelisting_likes_servicelisting_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelisting',
            name='favorite_flagged',
            field=models.ManyToManyField(blank=True, related_name='services_favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
