# Generated by Django 5.2.1 on 2025-07-11 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_servicelisting_favorite_flagged'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDetailSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('text_image', 'Text with Image'), ('list', 'List View'), ('text_only', 'Text Only'), ('image_only', 'Image Only')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which sections appear')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_sections/')),
                ('list_items', models.JSONField(blank=True, default=list, help_text='JSON array of list items for list sections')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_sections', to='services.servicelisting')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
