# Generated by Django 5.2.1 on 2025-07-24 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_availability_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelisting',
            name='category',
            field=models.CharField(choices=[('Legal', 'Legal Services'), ('Accounting', 'Accounting & Finance'), ('Consulting', 'Business Consulting'), ('HR', 'Human Resources'), ('Marketing', 'Marketing & Advertising'), ('Healthcare', 'Healthcare Services'), ('Fitness', 'Fitness & Training'), ('MentalHealth', 'Mental Health'), ('Nutrition', 'Nutrition & Diet'), ('Beauty', 'Beauty & Cosmetics'), ('Design', 'Graphic & Design'), ('Development', 'Web & App Development'), ('Writing', 'Writing & Editing'), ('Photography', 'Photography'), ('Video', 'Video & Animation'), ('Music', 'Music & Audio'), ('Construction', 'Construction & Remodeling'), ('Electrical', 'Electrical Services'), ('Plumbing', 'Plumbing'), ('Cleaning', 'Cleaning Services'), ('Landscaping', 'Landscaping & Gardening'), ('Tutoring', 'Tutoring & Lessons'), ('Language', 'Language Teaching'), ('MusicLessons', 'Music Lessons'), ('TestPrep', 'Test Preparation'), ('Workshops', 'Workshops & Classes'), ('IT', 'IT Support'), ('Cybersecurity', 'Cybersecurity'), ('Data', 'Data Analytics'), ('AI', 'Artificial Intelligence'), ('Blockchain', 'Blockchain Services'), ('Events', 'Event Planning'), ('Catering', 'Catering Services'), ('Photobooth', 'Photobooth Rental'), ('DJ', 'DJ Services'), ('Delivery', 'Delivery Services'), ('Transport', 'Transportation'), ('Logistics', 'Logistics Services'), ('Pet', 'Pet Services'), ('Senior', 'Senior Care'), ('Childcare', 'Childcare'), ('PA', 'Personal Assistant'), ('VA', 'Virtual Assistant'), ('Other', 'Other')], default='Other'),
        ),
        migrations.AddField(
            model_name='servicelisting',
            name='location',
            field=models.CharField(default='Bulgaria/Sofia', help_text='Specify location in the format Country/(city, province, village etc.)', max_length=100, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
    ]
