# Generated by Django 5.2.1 on 2025-08-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_alter_availability_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelisting',
            name='deactivation_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
