# Generated by Django 5.2.1 on 2025-08-03 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_servicelisting_deactivation_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelisting',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicelisting',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deactivated_services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicelisting',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
