# Generated by Django 5.2.1 on 2025-07-16 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_provideravailability_weeklytimeslot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='provider',
            field=models.ForeignKey(limit_choices_to={'user_type': 'Provider'}, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seeker',
            field=models.ForeignKey(limit_choices_to={'user_type': 'Seeker'}, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='provideravailability',
            name='provider',
            field=models.OneToOneField(limit_choices_to={'user_type': 'Provider'}, on_delete=django.db.models.deletion.CASCADE, related_name='availability', to=settings.AUTH_USER_MODEL),
        ),
    ]
