# Generated by Django 5.2.1 on 2025-07-24 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_provider_alter_booking_seeker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='appointment_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 24, 19, 4, 50, 738689, tzinfo=datetime.timezone.utc)),
        ),
    ]
