# Generated by Django 5.2.1 on 2025-07-24 19:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_appointment_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='booking',
            name='stripe_customer_id',
            field=models.CharField(default='', max_length=512, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='The Stripe subscription ID', max_length=512, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='appointment_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
