# Generated by Django 5.2.1 on 2025-07-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_amount_paid_booking_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=512, null=True, unique=True),
        ),
    ]
