# Generated by Django 5.2.1 on 2025-07-27 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_booking_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='stripe_subscription_id',
        ),
    ]
