# Generated by Django 5.2.1 on 2025-07-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_remove_booking_stripe_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='stripe_invoice_id',
            field=models.CharField(blank=True, help_text='The Stripe subscription ID', null=True, unique=True),
        ),
    ]
