# Generated by Django 5.2.1 on 2025-08-06 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_booking_provider_alter_booking_seeker_and_more'),
        ('services', '0015_deletedservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='provideravailability',
            name='service',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_availability', to='services.servicelisting'),
        ),
    ]
