# Generated by Django 5.2.1 on 2025-08-06 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_provideravailability_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provideravailability',
            name='service',
        ),
    ]
