# Generated by Django 5.2.1 on 2025-08-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='chat_thumbnails/'),
        ),
    ]
