# Generated by Django 5.2.1 on 2025-06-07 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='provider',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'ProviderProvider'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='review_type',
            field=models.CharField(choices=[('provider', 'Service Provider Review'), ('service', 'Specific Service Review'), ('website', 'Website/Platform Review')], default='website', max_length=10),
        ),
        migrations.AddField(
            model_name='review',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='services.servicelisting'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('provider__isnull', False), ('review_type', 'provider'), ('service__isnull', True)), models.Q(('provider__isnull', True), ('review_type', 'service'), ('service__isnull', False)), models.Q(('provider__isnull', True), ('review_type', 'website'), ('service__isnull', True)), _connector='OR'), name='consistent_review_type'),
        ),
    ]
