# Generated by Django 5.2.1 on 2025-07-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_providerreview_reviewer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerreview',
            name='comment',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='providerreview',
            name='main_caption',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='comment',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='main_caption',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='websitereview',
            name='comment',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='websitereview',
            name='main_caption',
            field=models.CharField(max_length=40),
        ),
    ]
