# Generated by Django 5.2.1 on 2025-08-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_providerreview_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerreview',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userreview',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='websitereview',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
